version: "3.8"

services:
  movieweb:
    build:
      context: .
      args:
        PWA_ENABLED: "true"
        TMDB_READ_API_KEY: ""
        CORS_PROXY_URL: ""
        BACKEND_URL: ""
    ports:
      - "80:80"
    restart: unless-stopped
